#!/usr/bin/expect -f
set arg1 [lindex $argv 0]
log_user 0
set timeout 5
spawn nprocons --user user-name $arg1
match_max 100000
expect {
 eof { send_user "\nNo such machine in mapping\n"; exit 1 } 
 "Password:" {
   send "Passw0rd\r"
   exp_continue	}
}
expect -exact "^\]\r"
send -- "\r"
expect {
  timeout { send_user "\nFailed to get nprocons prompt\n"; exit 1 }
  "login: " { send_user "\nAble to get login prompt\n"}
}	
send -- ""
expect -exact "-> "
send -- "exit\r"
expect eof
